version: "3"
       
services:
        nexus:
                image: sonatype/nexus3
                container_name: nexus-repo
                #restart: always
                ports: 
                        - 8081:8081
                volumes:
                        - ~/nexus-data:/nexus-data
                networks:
                        - usine-network
        jenkins: 
                image: jenkins/jenkins:lts
                container_name: jenkins-master
                privileged: true
                user: root
                ports:
                        - 8080:8080
                        - 50000:50000
                volumes:
                        - ~/jenkins:/var/jenkins_home
                        - /var/run/docker.sock:/var/run/docker.sock
                        - /usr/local/bin/docker:/usr/local/bin/docker
                networks:
                        - usine-network

#cette partie est spécifiée pour l'environnement devolab
#pour un environnement autre, il faudra vérifier la 
#concordance des trames réseau entre la machine et docker                          
networks:
        usine-network:
                driver: bridge
                driver_opts:
                        com.docker.network.driver.mtu: 1450
